name: build

on: workflow_dispatch

jobs:
  
  macos:
    name: ${{ matrix.config }} macOS 64-bit (${{ matrix.c }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Release]
        include:
          - c: clang
            cxx: clang++
            ld: lld

    steps:
    - name: Install tools
      run: brew install ninja

    - name: Update compiler
      id: compiler
      run: |
        # see https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#language-and-runtime
        # clang 13.0.0 hangs while building cg_vm.c (related to branching macro UOP()) => use clang 13.0.1
        echo "::set-output name=c_compiler::$(brew --prefix llvm@13)/bin/${{ matrix.c }}"
        echo "::set-output name=cxx_compiler::$(brew --prefix llvm@13)/bin/${{ matrix.cxx }}"
        echo "::set-output name=linker::$(brew --prefix llvm@13)/bin/${{ matrix.ld }}"

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure
      run: cmake
        -S .
        -B build
        -G Ninja
        -DBINARY_NAME=cgamex86_64
        -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -m64"
        -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -m64"
        -DCMAKE_C_COMPILER=${{ steps.compiler.outputs.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ steps.compiler.outputs.cxx_compiler }}
        -DCMAKE_LINKER=${{ steps.compiler.outputs.linker }}

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: build/cgame_proxymod
      run: ctest --no-tests=error --output-on-failure

    - name: Install
      if: matrix.c == 'clang' && matrix.config == 'Release'
      run: cmake --install build --prefix bin --strip

    - uses: actions/upload-artifact@v3
      if: matrix.c == 'clang' && matrix.config == 'Release'
      with:
        name: artifact
        path: bin/*.dylib
        if-no-files-found: error
        retention-days: 5
